apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-exporter
  template:
    metadata:
      labels:
        app: adguard-exporter
    spec:
      containers:
        - name: adguard-exporter
          image: ebrianne/adguard-exporter:latest
          env:
            - name: adguard_protocol
              value: "http"
            - name: adguard_hostname
              value: "192.168.1.203"
            - name: adguard_port
              value: "80"
            - name: adguard_username
              value: "admin"
            - name: adguard_password
              value: "Lx90lx90lx90!"
            - name: port
              value: "9617"
          ports:
            - containerPort: 9617
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-exporter
  namespace: default
spec:
  selector:
    app: adguard-exporter
  ports:
    - name: metrics
      port: 9617
      targetPort: 9617
