apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: adguard-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: adguard-exporter
  endpoints:
    - port: metrics
      interval: 30s
      scheme: http
